addons:
  ssh_known_hosts:
  - 138.68.142.81
language: node_js
node_js:
- '8'
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
- provider: surge
  skip_cleanup: true
  project: "./surge/"
  domain: quadrakill.placeofthin.gs
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_c494a9867e56_key -iv $encrypted_c494a9867e56_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- chmod +x ./deploy.sh
- "./surge_deploy.sh"
env:
  secure: "cR7VIaz5WaM3eBOop/+HPf9k4WOp7bXwy80AX+ZgE5m6PwFe+vUEyrjPZbTWY3gH02qcy/80OQ2TsLVJctuXwuBVMi2/fODzld9Qqd3nUAU36aOm1xqUWOWmjJKHiBLeJ/rV5JLkEHenZWqQmhBxJRpDU1FoLOKiFLRyPoy66BZRUEkngwInEfZC1s6cQE0E1xXJWS+Vqx1C4FYLBrxnDq3nTOCPNnPzst8uS2Eu+UZUq/hb34n7CjCge6CxRUl/W4f/s1eB/G96EgMAuUEnkvsWVeEp5mVZPLHkGZ43tCZwva2epByANbIxS+bavOiz3pEtazDOCNBeKo7OkQxVA1gXpPpWmoyvYpR3GU6M8gxeFchTeEIPbpNN4G0rsAKG3JduZoUCsnYUj9cXlj3Y592G+hBEXzRopj/xhJH/mOZLVIqRDrDHiFk2hxi4QzugqnYv7OpwLG03uBgdGZnBaD0f/HX/lPXuiU6dbu87bH1MT83o/rhldcaf8ZOG1HH6C9gy7wMAzfzGj4FDi7w1UzCoczZ8j3btNuMFkvj8xP5aXp6gdff+GdyfCUoRCt2q3MR4OGbOWD+4Rr023tx/SGBydRWOmBmOlq9HxU18hQmNlUfslgiiSLhYlSMmS6kFfQKtk7nLnifzSPt2y97bEfjFdMjl+DQTcdj9ig28Y3w="
