addons:
  ssh_known_hosts:
  - 138.68.142.81
language: node_js
node_js:
- '8'
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
- provider: surge
  skip_cleanup: true
  project: "./surge/"
  domain: quadrakill.placeofthin.gs
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_c494a9867e56_key -iv $encrypted_c494a9867e56_iv
  -in deploy_rsa.enc -out deploy_rsa -d
